name: CI - Detect Secrets, SAST, Sonar, Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Detect secrets
        uses: RobertFischer/detect-secrets-action@v2
        with:
          output: secrets.json

      - name: Upload secrets report
        uses: actions/upload-artifact@v3
        with:
          name: secrets-report
          path: secrets.json
